name: mohaeb_13_7_2022
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  sqflite: ^2.0.2
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  math_expressions: ^2.3.0
  gradient_widgets: ^0.6.0
  back_button_interceptor: ^5.0.2
  image_picker: ^0.8.4+11
  get:
    #  image_picker:
  dio: ^4.0.4
    #  image_gallery_saver: ^1.7.1
  flutter_typeahead: ^3.2.4
#  simple_animations: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  assets:
    - images/

  uses-material-design: true
